CXX_SOURCES = local_waypoint_transfer.cpp
USE_C_API = true
CXXFLAGS += -std=c++17 -O2
INCLUDE += -I"$(abspath ../../..)"
WEBOTS_HOME_PATH ?= $(WEBOTS_HOME)/Contents
include $(WEBOTS_HOME_PATH)/resources/Makefile.include
